### PR TITLE
fix(vm): always stop the VM even on SSM errors

### LINKED ISSUE #206: VM won't stop when verifyContribution throws

### PR DESCRIPTION
**Pull request by ctrlc03**
fix #206

### CODE REVIEW

File: packages/backend/src/functions/circuit.ts [hunk 1]
```diff
@@ -271,6 +271,9 @@ const waitForVMCommandExecution = (ssm: SSMClient, vmInstanceId: string, command
             } catch (error: any) {
                 printLog(`Invalid command ${commandId} execution`, LogLevel.DEBUG)
 
+                const ec2 = await createEC2Client()
+                await stopEC2Instance(ec2, vmInstanceId)
```
Comment (baumstern) [inline packages/backend/src/functions/circuit.ts:275]: Perhaps adding a try-catch block here, similar to what's done below, would be a good idea.

Comment (ctrlc03) [reply packages/backend/src/functions/circuit.ts:275]: sure thing

**Review by baumstern — APPROVED** [review]
LGTM
